name: LMS
version: @version@-@apiversion@
author: DartPower
website: https://github.com/dptmc/LMS
main: io.dpteam.LMS.Main
commands:
  event:
    description: 'Staff, start an event.'
permissions:
  lms.event:
    description: Perm to start an event.